version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    volumes:
      - cert-vol:/var/lib/https-portal
    ports:
      - '80:80'
      - '443:443'
    networks:
      - mynet
    depends_on:
      - web
    environment:
      STAGE: local

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - tmp-vol:/shared/tmp
    networks:
      - mynet
    depends_on:
      - app
    environment:
      TZ: "Asia/Tokyo"
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - tmp-vol:/shared/tmp
    command: bundle exec puma -C config/puma.rb
    networks:
      - mynet
    depends_on:
      - db
    environment:
      TZ: "Asia/Tokyo"
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - mynet
    environment:
      TZ: "Asia/Tokyo"

volumes:
  tmp-vol:
  db-vol:
  cert-vol:
networks:
  mynet:
