version: '3'
services:
  web:
    restart: always
  app:
    env_file:
      - .env.production
    command: bash -c "bundle exec rails assets:precompile && bundle exec puma -C config/puma.rb"
    restart: always
  db:
    env_file:
      - .env.production
    restart: always
